---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-mdns
spec:
  template:
    spec:
      containers:
      - name: ingress-mdns
        image: localhost:32000/dev/ingress-mdns
        volumeMounts:
        - name: ingress-mdns
          mountPath: /ingress-mdns
        - name: temp
          mountPath: /tmp
      volumes:
      - name: ingress-mdns
        hostPath:
          path: /home/aim/Workspace/operations/apps/ingress-mdns
      - name: yarn-cache
        emptyDir: {}
      - name: temp
        emptyDir: {}
