apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: ingress-mdns
resources:
- ../base
patchesStrategicMerge:
- ingress-mdns.yaml
